version: '3'
services:
  app:
    build: .
    command: sh -c "npm install && npm install -g knex && knex migrate:latest && npm start"
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
  db:
    image: postgres:latest
    expose:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
